### ISSUE TITLE
Problems with the PET extension for QIN-HEADNECK demo subject

### ISSUE THREAD

**Issue by fedorov** [QIICR/Slicer-SUVFactorCalculator#1]
I was trying to essentially reproduce in Slicer what you do in your demo video (https://www.youtube.com/watch?v=d3M7zzgEcj4, subject 57, timepoint 1), and failed.

It looks like SUV calculation is failing. The messages in the error log are not particularly helpful:

```
SUV Factor Calculator standard error:
Missing some parameters...
ERROR: Failed to compute SUV
SUV Factor Calculator completed with errors
```

SUV computation works just fine for subject 4, as an example.

Can you investigate what is going on?

Among other things, can you look into improving error reporting of the SUV to give more details when a problem occurs?

**Comment by fedorov** [comment]
I think this is the same issue as https://github.com/QIICR/Slicer-PETDICOMExtension/issues/2

**Comment by ejulrich** [comment]
This repository is deprecated and superseded by https://github.com/QIICR/Slicer-PETDICOMExtension
